"""``registry_tools readme`` — the README mod table, generated from ``index.json`` (Requirement 8.10).

A registry README carries one table of what the registry lists, between two
markers the tooling owns::

    <!-- mods:begin -->
    | Mod | Newest | Record | Kinds | Contact | Compatibility |
    …
    <!-- mods:end -->

The table is **derived** — like ``index.json`` itself — so it can never drift
from the records: ``registry_tools readme REPO`` rewrites the block from the
committed ``index.json`` (plus each mod's ``contact`` from ``mods/<id>/mod.json``),
and ``registry_tools readme REPO --check`` fails when the committed README
differs from the regenerated one (the gate of the internal package runs it).
A README without the markers is left alone by ``--check`` only when the caller
allows it; the bootstrap's template always carries them.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .repo import RegistryRepo, RepoError

__all__ = ["MARK_BEGIN", "MARK_END", "readme_matches", "render_table", "update_readme"]

MARK_BEGIN = "<!-- mods:begin -->"
MARK_END = "<!-- mods:end -->"
_GENERATED_NOTE = "<!-- generated by `registry_tools readme` from index.json; edit the records, not this table -->"


def _newest(versions: list[dict[str, Any]]) -> dict[str, Any] | None:
    from floofy_core.semver import InvalidVersion, Version  # noqa: PLC0415

    parsed: list[tuple[Version, dict[str, Any]]] = []
    for version in versions:
        try:
            parsed.append((Version.parse(str(version.get("version"))), version))
        except InvalidVersion:
            continue
    return max(parsed, key=lambda item: item[0])[1] if parsed else None


def _record_cell(version: dict[str, Any] | None) -> str:
    if version is None:
        return "—"
    link = version.get("link")
    if isinstance(link, dict):
        where = f" ({link['path']})" if isinstance(link.get("path"), str) and link["path"] else ""
        point = str(link.get("commit") or "")[:12] or link.get("tag") or "?"
        return f"link: `{link.get('repo')}`{where} at `{point}`"
    return "archive"


def _compat_cell(versions: list[dict[str, Any]]) -> str:
    cells: dict[str, str] = {}
    for version in versions:
        for host, verdict in (version.get("compat") or {}).items():
            cells[f"{version.get('version')} on {host}"] = str(verdict)
    return "; ".join(f"{k}: {v}" for k, v in sorted(cells.items())) or "no matrix cell yet"


def _contact(repo: RegistryRepo | None, mod_id: str) -> str:
    if repo is None or not (repo.mods_dir / mod_id).is_dir():
        return "—"
    try:
        curated = repo.read_mod(mod_id).curated
    except (RepoError, OSError):
        return "—"
    contact = curated.get("contact")
    return f"`{contact}`" if isinstance(contact, str) and contact else "—"


def render_table(index: dict[str, Any], repo: RegistryRepo | None = None) -> str:
    """The Markdown block between the markers (markers included) for ``index``."""
    lines = [MARK_BEGIN, _GENERATED_NOTE, "| Mod | Newest | Record | Kinds | Contact | Compatibility |", "|---|---|---|---|---|---|"]
    mods = sorted((m for m in index.get("mods", []) if isinstance(m, dict) and isinstance(m.get("id"), str)), key=lambda m: m["id"])
    for mod in mods:
        versions = [v for v in (mod.get("versions") or []) if isinstance(v, dict)]
        newest = _newest(versions)
        kinds = ", ".join(newest.get("kinds") or []) if newest else "—"
        name = str(mod.get("name") or mod["id"]).replace("|", "\\|")
        lines.append(f"| `{mod['id']}` — {name} | {newest.get('version') if newest else '—'} | {_record_cell(newest)} | {kinds or '—'} | {_contact(repo, mod['id'])} | {_compat_cell(versions)} |")
    if not mods:
        lines.append("| *(no mods listed yet)* | | | | | |")
    lines.append(MARK_END)
    return "\n".join(lines)


def _splice(text: str, table: str) -> str | None:
    start = text.find(MARK_BEGIN)
    end = text.find(MARK_END)
    if start < 0 or end < 0 or end < start:
        return None
    return text[:start] + table + text[end + len(MARK_END):]


def update_readme(repo: RegistryRepo, *, index: dict[str, Any] | None = None, readme: Path | None = None) -> tuple[bool, Path]:
    """Rewrite the table block of ``README.md`` from ``index.json``; returns ``(changed, path)``. A README without markers gets the block appended."""
    path = readme or repo.root / "README.md"
    document = index if index is not None else json.loads(repo.index_path.read_text(encoding="utf-8"))
    table = render_table(document, repo)
    text = path.read_text(encoding="utf-8") if path.is_file() else ""
    spliced = _splice(text, table)
    if spliced is None:
        spliced = text.rstrip("\n") + "\n\n## Mods\n\n" + table + "\n"
    changed = spliced != text
    if changed:
        path.write_text(spliced, encoding="utf-8")
    return changed, path


def readme_matches(repo: RegistryRepo, *, index: dict[str, Any] | None = None, readme: Path | None = None) -> tuple[bool, str]:
    """Whether the committed README's table equals the one rebuilt from ``index.json``."""
    path = readme or repo.root / "README.md"
    if not path.is_file():
        return False, f"{path} does not exist"
    document = index if index is not None else json.loads(repo.index_path.read_text(encoding="utf-8"))
    text = path.read_text(encoding="utf-8")
    if MARK_BEGIN not in text or MARK_END not in text:
        return False, f"{path} has no {MARK_BEGIN} … {MARK_END} block; run `registry_tools readme`"
    if _splice(text, render_table(document, repo)) != text:
        return False, f"{path}: the mod table is stale — run `registry_tools readme` and commit (Requirement 8.10)"
    return True, f"{path}: the mod table is up to date with index.json"
