"""The registry repository layout (Requirement 8.2, 8.9; the Obsidian model).

A registry is a git repository curated by pull request. Mod files are **not**
in it — they are release assets of the mod's own repository (public edition) or
archives the registry package carries beside the records (internal edition,
transitional); the records only name them with ``url``, ``sha256`` and ``size``.
A **link record** names no file at all: it points at the mod's repository and
the mod's directory inside it, pinned at a **commit** — the version is located
by that commit, never by a tag — and the index carries the commit, the
canonical-manifest hash and the checkout's files so a client can fetch and
verify (Requirement 8.9)::

    registry.json                       the registry's identity (below)
    mods/<id>/mod.json                  optional curated record: repo, tags, links, icon
    mods/<id>/<version>/floofy.json     the mod's manifest, copied verbatim from the release
    mods/<id>/<version>/release.json    {"publishedAt", "channel", "tag"?,
                                         "files": [{url, sha256, size, name}]              — an asset record, or
                                         "link": {repo, commit, manifestSha256, path?, ref?},
                                         "files": [{path, sha256, size}]                    — a link record,
                                         "app": {"name", "subdirectory"}?, "yanked": "<reason>"?,
                                         "changelog": "<https URL of the release notes>"?}
    compat.json (+ .sig)                the compatibility matrix the Forge maintains (Requirement 9)
    index.json (+ .sig)                 generated by `registry_tools build`; never edited by hand
    app-registry.json                   generated for app-kind mods (Requirement 8.6)
    masquerade-allow.txt                ids the curators cleared of the host-name check

``registry.json``::

    {"schema": 1, "source": "github:floofycrew/floofycrew-registry", "keyId": "<16 hex>",
     "archiveUrlTemplate": "https://…/{id}-{version}/{file}", "hostRegistry": {"repo": "…", "branch": "main"},
     "recordKind": "archive" | "link", "repoUrlPattern": "^https://…$"}

``source`` is the label written into ``index.json`` (informational for clients);
``keyId`` names the key the index must be signed with (``verify`` and CI check
it); ``archiveUrlTemplate`` is what ``init_registry_repo.sh`` and the release
tooling use to spell a file URL (``{id}``, ``{version}``, ``{tag}``, ``{file}``);
``recordKind`` is the shape new records default to; ``repoUrlPattern`` (optional)
is the regular expression every link record's ``repo`` must match — the
internal registry pins its forge by pattern (Requirement 8.10).
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterator

from floofy_core.semver import InvalidVersion, Version

__all__ = ["ModRecord", "RegistryRepo", "RepoError", "VersionRecord", "read_json"]

ID_RE = re.compile(r"^[a-z][a-z0-9_-]{1,63}$")


class RepoError(ValueError):
    """A registry repository that cannot be read as the layout above."""


def read_json(path: Path) -> Any:
    try:
        return json.loads(Path(path).read_text(encoding="utf-8"))
    except FileNotFoundError:
        raise RepoError(f"{path}: missing") from None
    except (OSError, ValueError) as exc:
        raise RepoError(f"{path}: {exc}") from exc


@dataclass
class VersionRecord:
    """One ``mods/<id>/<version>/`` directory."""

    mod_id: str
    version: str
    directory: Path
    manifest: dict[str, Any]
    release: dict[str, Any]

    @property
    def parsed(self) -> Version:
        return Version.parse(self.version)

    @property
    def files(self) -> list[dict[str, Any]]:
        return [dict(f) for f in self.release.get("files") or [] if isinstance(f, dict)]

    @property
    def link(self) -> dict[str, Any] | None:
        """The link record's ``{repo, commit?, manifestSha256?, path?, ref?, tag?}`` (Requirement 8.9), ``None`` for an asset record."""
        link = self.release.get("link")
        return dict(link) if isinstance(link, dict) and isinstance(link.get("repo"), str) else None

    @property
    def is_link(self) -> bool:
        return self.link is not None

    @property
    def link_tag(self) -> str | None:
        """A legacy link record's tag (``link.tag``, else a ``tag`` the release declares); ``None`` for a commit-pinned record.

        Since records pin commits, no tag locates a version: this is read only to
        resolve a record made before that, and to render what such a record says.
        """
        link = self.link or {}
        tag = link.get("tag")
        if isinstance(tag, str) and tag:
            return tag
        declared = self.release.get("tag")
        return declared if isinstance(declared, str) and declared else None

    @property
    def link_commit(self) -> str | None:
        """The commit a link record pins (``link.commit``), ``None`` while the record is unresolved."""
        link = self.link or {}
        commit = str(link.get("commit") or "").lower()
        return commit or None

    @property
    def link_ref(self) -> str | None:
        """The branch the record is made from and refreshed against (``link.ref``); ``None`` means the repository's default branch."""
        link = self.link or {}
        ref = link.get("ref")
        return ref if isinstance(ref, str) and ref else None

    @property
    def link_point(self) -> str:
        """What the record is fetched at, for messages: the commit (short), else the legacy tag, else the default branch."""
        if self.link_commit:
            return self.link_commit[:12]
        return self.link_tag or (self.link_ref or "the default branch")

    @property
    def link_resolved(self) -> bool:
        """Whether the link record carries what the index needs: ``commit``, ``manifestSha256`` and the checkout's ``files[]``."""
        link = self.link or {}
        return bool(link.get("commit")) and bool(link.get("manifestSha256")) and bool(self.files) and all("path" in f and "url" not in f for f in self.files)

    @property
    def tag(self) -> str:
        tag = self.release.get("tag")
        return tag if isinstance(tag, str) and tag else self.version

    @property
    def parts(self) -> list[dict[str, Any]]:
        return [p for p in self.manifest.get("parts") or [] if isinstance(p, dict)]

    @property
    def kinds(self) -> list[str]:
        return sorted({str(p.get("kind")) for p in self.parts if p.get("kind")})

    def app_facts(self) -> dict[str, Any] | None:
        """``{name, subdirectory}`` when the mod is a pure App Kit app (a single ``app`` part), else ``None`` (Requirement 8.6).

        ``release.json``'s ``app`` block wins (it may name the app.json's own
        ``name``); otherwise the app is assumed to be named after the mod and to
        live in the directory holding the part's ``app.json``.
        """
        parts = self.parts
        if len(parts) != 1 or parts[0].get("kind") != "app":
            return None
        declared = self.release.get("app") if isinstance(self.release.get("app"), dict) else {}
        path = str(parts[0].get("path") or "app.json")
        subdirectory = declared.get("subdirectory") if isinstance(declared.get("subdirectory"), str) else str(Path(path).parent).replace("\\", "/")
        if subdirectory in (".", ""):
            subdirectory = ""
        name = declared.get("name") if isinstance(declared.get("name"), str) and declared.get("name") else self.mod_id
        return {"name": name, "subdirectory": subdirectory}


@dataclass
class ModRecord:
    """``mods/<id>/``: the curated ``mod.json`` (optional) plus every version directory."""

    mod_id: str
    directory: Path
    curated: dict[str, Any] = field(default_factory=dict)
    versions: list[VersionRecord] = field(default_factory=list)

    @property
    def newest(self) -> VersionRecord | None:
        return max(self.versions, key=lambda v: v.parsed) if self.versions else None

    def field(self, name: str, default: Any = None) -> Any:
        """A mod-level field: the curated record wins, then the newest manifest."""
        if name in self.curated:
            return self.curated[name]
        newest = self.newest
        if newest is not None and name in newest.manifest:
            return newest.manifest[name]
        return default

    def repo(self) -> str | None:
        """The source repository: ``mod.json`` ``repo``, else a manifest ``links`` entry named repo/source/repository."""
        candidate = self.curated.get("repo")
        if isinstance(candidate, str) and candidate:
            return candidate
        newest = self.newest
        links = newest.manifest.get("links") if newest is not None and isinstance(newest.manifest.get("links"), dict) else {}
        for key in ("repo", "repository", "source", "homepage"):
            if isinstance(links.get(key), str) and links[key]:
                return links[key]
        return None


@dataclass
class RegistryRepo:
    root: Path
    config: dict[str, Any]

    @classmethod
    def load(cls, root: Path) -> "RegistryRepo":
        root = Path(root)
        if not (root / "registry.json").is_file():
            raise RepoError(f"{root}: no registry.json (not a registry repository)")
        config = read_json(root / "registry.json")
        if not isinstance(config, dict) or config.get("schema") != 1 or not isinstance(config.get("source"), str):
            raise RepoError(f"{root}/registry.json: expected {{\"schema\": 1, \"source\": \"…\", …}}")
        return cls(root, config)

    @property
    def source(self) -> str:
        return str(self.config["source"])

    @property
    def key_id(self) -> str | None:
        kid = self.config.get("keyId")
        return kid if isinstance(kid, str) and kid else None

    @property
    def mods_dir(self) -> Path:
        return self.root / "mods"

    @property
    def index_path(self) -> Path:
        return self.root / "index.json"

    @property
    def compat_path(self) -> Path:
        return self.root / "compat.json"

    @property
    def app_registry_path(self) -> Path:
        return self.root / "app-registry.json"

    @property
    def allowlist_path(self) -> Path:
        return self.root / "masquerade-allow.txt"

    def archive_url(self, *, mod_id: str, version: str, tag: str, file: str) -> str | None:
        template = self.config.get("archiveUrlTemplate")
        if not isinstance(template, str):
            return None
        return template.replace("{id}", mod_id).replace("{version}", version).replace("{tag}", tag).replace("{file}", file)

    @property
    def record_kind(self) -> str:
        """``link`` or ``archive`` — the shape new records take (``registry.json`` ``recordKind``, default ``archive``)."""
        kind = self.config.get("recordKind")
        return kind if kind in ("link", "archive") else "archive"

    @property
    def repo_url_pattern(self) -> str | None:
        """The regular expression every link record's ``repo`` must match (``registry.json`` ``repoUrlPattern``), or ``None`` when unpinned."""
        pattern = self.config.get("repoUrlPattern")
        return pattern if isinstance(pattern, str) and pattern else None

    def version_dir(self, mod_id: str, version: str) -> Path:
        return self.mods_dir / mod_id / version

    def read_version(self, mod_id: str, version: str) -> VersionRecord:
        directory = self.version_dir(mod_id, version)
        manifest = read_json(directory / "floofy.json")
        release = read_json(directory / "release.json")
        if not isinstance(manifest, dict) or not isinstance(release, dict):
            raise RepoError(f"{directory}: floofy.json and release.json must be JSON objects")
        if manifest.get("id") != mod_id:
            raise RepoError(f"{directory}/floofy.json: id {manifest.get('id')!r} does not match the directory {mod_id!r}")
        if manifest.get("version") != version:
            raise RepoError(f"{directory}/floofy.json: version {manifest.get('version')!r} does not match the directory {version!r}")
        try:
            Version.parse(version)
        except InvalidVersion as exc:
            raise RepoError(f"{directory}: {exc}") from exc
        return VersionRecord(mod_id, version, directory, manifest, release)

    def read_mod(self, mod_id: str) -> ModRecord:
        directory = self.mods_dir / mod_id
        if not ID_RE.match(mod_id):
            raise RepoError(f"{directory}: {mod_id!r} is not a valid mod id")
        curated = read_json(directory / "mod.json") if (directory / "mod.json").is_file() else {}
        if not isinstance(curated, dict):
            raise RepoError(f"{directory}/mod.json: not a JSON object")
        record = ModRecord(mod_id, directory, curated)
        for child in sorted(directory.iterdir()):
            if child.is_dir() and not child.name.startswith("."):
                record.versions.append(self.read_version(mod_id, child.name))
        record.versions.sort(key=lambda v: v.parsed)
        return record

    def mods(self) -> Iterator[ModRecord]:
        if not self.mods_dir.is_dir():
            return
        for child in sorted(self.mods_dir.iterdir()):
            if child.is_dir() and not child.name.startswith("."):
                yield self.read_mod(child.name)

    def allowlist(self) -> set[str]:
        """Mod ids the curators cleared of the host-name masquerade check (one per line, ``#`` comments)."""
        try:
            lines = self.allowlist_path.read_text(encoding="utf-8").splitlines()
        except FileNotFoundError:
            return set()
        return {line.split("#", 1)[0].strip() for line in lines if line.split("#", 1)[0].strip()}
