#!/usr/bin/env python3
"""Assemble the public release tree of FloofyCrew from a checkout (task 9.2; Requirement 10.5).

The external track ships FloofyCrew as **GitHub release assets** plus a generated
``loader-app`` branch, built from the shared core plus the **public** edition
adapter only (``--edition public``), so nothing in a public artifact names an
internal system (Requirement 10.2; the release workflow scans the unpacked tree
with ``scripts/check_no_internal_identifiers.py``). ``packaging/internal/build.py``
builds the same core with the internal adapter, and
``scripts/artifact_identity_report.py`` measures how much of the two trees is
byte-identical (Requirement 10.4).

Layout written into ``--out`` (default ``build/public/``)::

    dist/floofy.pyz                          the single-file manager (scripts/build_zipapp.py, public adapter)
    dist/floofycrew-<v>-py3-none-any.whl     the wheel (scripts/build_wheel.py): pip / pipx / the host venv
    dist/floofycrew-loader-app-<v>.zip       the Loader app as a deterministic archive
    dist/SHA256SUMS                          sha256 of every file under dist/ and app/floofycrew/**
    dist/supports.json                       copied from --supports when given
    app/floofycrew/                          the Loader app directory (published on the loader-app branch)
    app-registry.json                        this tree as a KiroCrew app registry: one row, the Loader app
    install.sh                               the one-liner installer (packaging/public/install.sh)
    README.md, RELEASE.md, .gitignore        what the tree is; version, supports, hashes

The release workflow (``.github/workflows/release.yml``) attaches ``dist/*`` to the
GitHub release for the tag and publishes everything but the binaries to the
orphan branch ``loader-app`` (a git tree the host can clone as a federated app
registry, the public twin of the internal data package). Every artifact is
reproducible — fixed timestamps, sorted entries — and ``--check`` builds twice
into temporary directories to prove it. Standard library only.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent
EDITION = "public"
DEFAULT_OUT = REPO_ROOT / "build" / "public"
ADAPTER_REGISTRY = REPO_ROOT / "editions" / "public" / "floofy_edition_public" / "registry.json"
ROW_FILE = HERE / "registry-row.json"
LOADER_APP_BRANCH = "loader-app"

sys.path.insert(0, str(REPO_ROOT / "scripts"))
sys.path.insert(0, str(REPO_ROOT / "registry-tools"))
sys.path.insert(0, str(REPO_ROOT / "floofy-core"))

import build_loader_app  # noqa: E402
import build_wheel  # noqa: E402
import build_zipapp  # noqa: E402
from registry_tools.bootstrap import deterministic_zip  # noqa: E402

__all__ = ["build_release", "floofycrew_repo", "package_files", "sha256_file", "tree_digest"]


def sha256_file(path: Path) -> str:
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def package_files(root: Path) -> list[Path]:
    return sorted(p for p in Path(root).rglob("*") if p.is_file() and ".git" not in p.relative_to(root).parts)


def tree_digest(root: Path) -> dict[str, str]:
    return {p.relative_to(root).as_posix(): sha256_file(p) for p in package_files(root)}


def floofycrew_repo() -> str:
    """The public FloofyCrew repository URL the edition adapter names (``https://github.com/<org>/FloofyCrew``)."""
    return str(json.loads(ADAPTER_REGISTRY.read_text(encoding="utf-8"))["floofycrewRepo"])


def _clear(out: Path) -> None:
    out.mkdir(parents=True, exist_ok=True)
    for child in out.iterdir():
        if child.name == ".git":
            continue
        if child.is_dir() and not child.is_symlink():
            shutil.rmtree(child)
        else:
            child.unlink()


def _app_registry(tag: str) -> list[dict]:
    """The one-row app registry: the Loader app in this tree on the ``loader-app`` branch (pinned to the release's copy when ``tag`` is given)."""
    row = dict(json.loads(ROW_FILE.read_text(encoding="utf-8"))["appRegistryRow"])
    if tag:
        row["branch"] = f"{LOADER_APP_BRANCH}-{tag}"
    return [row]


def _readme(version: str, repo: str) -> str:
    return f"""# FloofyCrew {version} — public release tree

**FloofyCrew** is an *unofficial* modding ecosystem for KiroCrew (not affiliated
with Kiro or KiroCrew): the `floofy` manager and the FloofyCrew Loader, a KiroCrew
App installed through the host's own App Kit. This tree is generated by
`packaging/public/build.py` in the source repository ({repo}) for every release;
it contains no KiroCrew code and never replaces the host (design DR-1).

| Path | What |
|---|---|
| `install.sh` | the one-liner installer: downloads the release assets over HTTPS, verifies them against `SHA256SUMS`, installs `~/.local/bin/floofy`, then `floofy init` |
| `app/floofycrew/` | the Loader app directory — what the host clones when this branch is listed as an app registry |
| `app-registry.json` | this tree as a KiroCrew app registry: one row, the Loader app |
| `dist/SHA256SUMS` | sha256 of the release assets and of `app/floofycrew/**` (the assets themselves are on the GitHub release) |
| `LICENSE`, `NOTICE.md`, `LICENSES/` | MIT, and the Apache-2.0 notices for the portions derived from KiroCrew |
| `RELEASE.md` | version, the host versions it supports, hashes |

Install: `curl -fsSL {repo.replace("https://github.com/", "https://raw.githubusercontent.com/")}/main/packaging/public/install.sh | sh`
(the script shows the one-time warning through `floofy init`; nothing is applied
before you acknowledge it). Documentation: `docs/` in the source repository.
"""


def _release_notes(version: str, tag: str, repo: str, supports: dict | None, sums: dict[str, str]) -> str:
    lines = [f"# floofycrew v{version} (public edition)", "", f"Release tag `{tag}` of {repo}.", "",
             "FloofyCrew is an **unofficial** modding ecosystem for KiroCrew. This release ships the `floofy`",
             "manager (zipapp and wheel) and the Loader app (a KiroCrew App), built from the shared core plus",
             "the public edition adapter. It contains no KiroCrew code and never replaces the host (design DR-1).", "",
             "## Supports (host versions with `loader: ok` in the compatibility matrix)", ""]
    if supports:
        for edition, channels in sorted(supports.items()):
            for channel, versions in sorted(channels.items()):
                lines.append(f"- {edition}/{channel}: {', '.join(versions) or '-'}")
    else:
        lines.append("- not recorded in this build (the release stage passes `--supports supports.json`)")
    lines += ["", "## Assets", "", "| File | sha256 |", "|---|---|"]
    for name, digest in sorted(sums.items()):
        lines.append(f"| `{name}` | `{digest}` |")
    lines += ["", "Verify a download: `sha256sum -c SHA256SUMS --ignore-missing` (Linux) or `shasum -a 256 -c SHA256SUMS --ignore-missing` (macOS).", ""]
    return "\n".join(lines)


def build_release(out: Path, *, supports: dict | None = None, interpreter: str = "/usr/bin/env python3.12", tag: str | None = None) -> dict:
    """Write the release tree at ``out`` and return ``{version, tag, out, sums, files}``."""
    out = Path(out).resolve()
    _clear(out)
    version = build_loader_app.core_version()
    tag = tag or f"v{version}"
    repo = floofycrew_repo()

    app_dir = out / "app" / "floofycrew"
    build_loader_app.build(app_dir, [EDITION])
    dist = out / "dist"
    dist.mkdir()
    build_zipapp.build(dist / "floofy.pyz", [EDITION], interpreter)
    build_wheel.build(dist, [EDITION])
    deterministic_zip(app_dir, dist / f"floofycrew-loader-app-{version}.zip", top="floofycrew")
    if supports is not None:
        (dist / "supports.json").write_text(json.dumps({"floofycrew": version, "supports": supports}, indent=2) + "\n", encoding="utf-8")

    shutil.copy2(HERE / "install.sh", out / "install.sh")
    # the licence and third-party notices (the themes.py port derives from KiroCrew, Apache-2.0)
    for name in ("LICENSE", "NOTICE.md", "LICENSES/Apache-2.0.txt"):
        target = out / name
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(REPO_ROOT / name, target)
    (out / "app-registry.json").write_text(json.dumps(_app_registry(tag), indent=2) + "\n", encoding="utf-8")
    (out / ".gitignore").write_text("__pycache__/\n*.pyc\n", encoding="utf-8")
    (out / "README.md").write_text(_readme(version, repo), encoding="utf-8")

    sums = {p.relative_to(out).as_posix(): sha256_file(p) for p in sorted(dist.iterdir()) if p.is_file()}
    sums.update({p.relative_to(out).as_posix(): sha256_file(p) for p in sorted(app_dir.rglob("*")) if p.is_file()})
    (dist / "SHA256SUMS").write_text("".join(f"{digest}  {name.removeprefix('dist/')}\n" for name, digest in sorted(sums.items())), encoding="utf-8")
    (out / "RELEASE.md").write_text(_release_notes(version, tag, repo, supports, {k: v for k, v in sums.items() if k.startswith("dist/")}), encoding="utf-8")
    return {"version": version, "tag": tag, "repo": repo, "out": str(out), "sums": sums, "files": [p.relative_to(out).as_posix() for p in package_files(out)]}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", default=str(DEFAULT_OUT), help=f"target directory (default {DEFAULT_OUT.relative_to(REPO_ROOT)})")
    parser.add_argument("--supports", default=None, metavar="JSON", help="a supports.json from the release stage to record")
    parser.add_argument("--python", default="/usr/bin/env python3.12", help="shebang interpreter of dist/floofy.pyz")
    parser.add_argument("--tag", default=None, help="the release tag being built (default v<version>); pins the app-registry row to loader-app-<tag>")
    parser.add_argument("--check", action="store_true", help="build twice into temporary directories and exit 1 unless both trees are byte-identical")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args(argv)
    supports = None
    if args.supports:
        document = json.loads(Path(args.supports).read_text(encoding="utf-8"))
        supports = document.get("supports", document)
    if args.check:
        with tempfile.TemporaryDirectory() as first, tempfile.TemporaryDirectory() as second:
            a = tree_digest(Path(build_release(Path(first) / "public", supports=supports, interpreter=args.python, tag=args.tag)["out"]))
            b = tree_digest(Path(build_release(Path(second) / "public", supports=supports, interpreter=args.python, tag=args.tag)["out"]))
        if a != b:
            print("NOT reproducible: " + ", ".join(sorted(set(a) ^ set(b) | {k for k in a if k in b and a[k] != b[k]})), file=sys.stderr)
            return 1
        print(f"OK: the public release tree builds reproducibly ({len(a)} files)")
        return 0
    result = build_release(Path(args.out), supports=supports, interpreter=args.python, tag=args.tag)
    if args.json:
        print(json.dumps(result, indent=2))
        return 0
    print(f"floofycrew {result['version']} ({result['tag']}) -> {result['out']} ({len(result['files'])} files)")
    for name, digest in sorted(result["sums"].items()):
        if name.startswith("dist/"):
            print(f"  {digest}  {name}")
    print(f"  app/floofycrew/: {sum(1 for n in result['sums'] if n.startswith('app/'))} files (hashes in dist/SHA256SUMS)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
